### PR TITLE
Provide SvelteBpmn Component + Cleanups

### LINKED ISSUE #1: Feature unmount, update and refs
As part of the [Diagram component](https://github.com/pinussilvestrus/bpmn-js-svelte-example/blob/master/src/components/Diagram.svelte) you may feature a bunch of additional Svelte core features and their interaction with bpmn-js:

* unMount
* update
* refs
* reactivity

So a more complete example could look something like this:

```html
<script>
  import { onMount, onDestroy } from 'svelte';

  import BpmnModeler from 'bpmn-js/lib/Modeler';

  const noop = () => {};

  export let xml = '';
  export let onLoaded = noop;
  export let onError = noop;

  let canvas;
  let modeler;

  onMount(() => {

    modeler = new BpmnModeler({
      container: canvas,
      keyboard: { bindTo: canvas }
    });;

    modeler.on('import.done', event => {

      const { error } = event;

      if (error) {
        return onError(error);
      }

      const canvas = modeler.get('canvas');
      canvas.zoom('fit-viewport');

      return onLoaded(event);
    });
  });

  onDestroy(() => {
    modeler.destroy();
  });

  // svelte reactivity: Re-import diagram whenever xml changes
  $: modeler.importXML(xml);
</script>

<style>
  .canvas {
    height: 100%;
    padding: 0;
    margin: 0;
  }
</style>

<div class="canvas" bind:this={canvas}>
</div>
```

### LINKED ISSUE #2: Consider move this example to a usable Svelte component
__What should we do?__

We could make this example as a usable Svelte component as we have it e.g. in the [react project](https://github.com/bpmn-io/react-bpmn)

__Why should we do it?__

Imagine building on top of changes described in #1 this could offer our users a good and ready-to-use component for there svelte applications.

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #1 
Closes #2 

This provides
* [x] some dependency updates + cleanups
* [x] updating the project to provide a usable Svelte component (`svelte-bpmn`) (cf. #2)
* [x] moving the example to the example directory
* [x] adding a bit more functionality to the component as suggested in #1 
* [x] adding GitHub action
* [ ] rename the project + release first version

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
I'm done with the initial implementation. Let's try to review + merge the first bits, anything else (more functionality for the component, an additional Viewer component) can be added on top.

**Review by nikku — CHANGES_REQUESTED** [review]
Looks good. I'd prefer to ship the viewer though, rather than the modeler, per default.

**Comment by pinussilvestrus** [comment]
Yeah, let's keep with the Viewer here until we don't support more features. +1 for adding a Modeler component on top.

**Comment by pinussilvestrus** [comment]
I added https://github.com/bpmn-io/bpmn-js-example-svelte/pull/3/commits/da9470a12c1295ac7f90b4ad436a0c0ec25cb3c4 on top to use the `Viewer` component.

**Review by nikku — APPROVED** [review]
:clap:

**Comment by nikku** [comment]
I did rename the project.

What is missing is updating links, e.g. in the awesome list (and potentially our examples).

**Comment by pinussilvestrus** [comment]
Thanks! I will follow up, updating the stuff and releasing the first version 👍

**Comment by pinussilvestrus** [comment]
Seems like the awesome list included the only reference: https://github.com/search?q=org%3Abpmn-io+bpmn-js-svelte-example

**Pull request merged**
